# Generated by Django 3.1.5 on 2021-05-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='end_date',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='start_date',
            field=models.CharField(max_length=250),
        ),
    ]
