# Generated by Django 3.1.5 on 2021-06-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20210527_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='start_date',
        ),
    ]
