# Generated by Django 3.1.5 on 2021-06-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20210616_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='text',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='movie_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='date',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
