# Generated by Django 3.1.5 on 2021-06-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20210616_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='movie_title',
            new_name='title',
        ),
    ]
