# Generated by Django 3.1.5 on 2021-05-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardimg',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
