# Generated by Django 3.1.5 on 2021-05-31 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210530_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
